version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      YSQL_ROOT_HOST: '172.28.0.1'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '8080:3306'
    expose:
      - '8080'
    volumes:
      - nestjsdb:/var/lib/mysql
volumes:
  nestjsdb: