version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      YSQL_ROOT_HOST: '172.28.0.1'
      MYSQL_DATABASE: 'nestjsdb'
      MYSQL_USER: 'Raoni111'
      MYSQL_PASSWORD: '2004123'
      MYSQL_ROOT_PASSWORD: '2004321'
    ports:
      - '8080:3306'
    expose:
      - '8080'
    volumes:
      - nestjsdb:/var/lib/mysql
volumes:
  nestjsdb: